name: Check installation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install pandoc
      uses: pandoc/actions/setup@v1
      with:
        version: "3.6.1"
    - name: Install zderad
      run: |
        pip install .
    - name: Test execution
      run: |
        zderad
